import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'commands',
    'configuration-reference',
    'action-modes',
    'cli-reference',
    'workflow-generation',
    'architecture',
    {
      type: 'category',
      label: 'Workflow Patterns',
      collapsed: false,
      items: ['flows/trunk-flow', 'flows/github-flow', 'flows/gitflow', 'flows/custom-flow']
    },
    'version-management',
    'examples',
    'troubleshooting',
    'error-handling',
    'testing-guide',
    'faq',
    'security',
    'roadmap',
    'contributing',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api'
        }
      ]
    }
  ]
}

export default sidebars
